#!/bin/bash
cat config.json | jq -rc ".clusters[]" | while read LINE; do
    name=$(echo ${LINE} | jq -r ".name")
    helm_bin_name=$(echo ${LINE} | jq -r ".helm")
    kubectl config use-context ${name}
    ${helm_bin_name} ls | tee -a charts.txt > /dev/null
done
cat charts.txt | grep -vi name | awk '{print $9}' | sort | uniq -c | sort -r
rm charts.txt
